#
# application.yml — главный конфигурационный файл Spring Boot.

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.

server:
  port: ${SPRING_SERVER_PORT:8080}

spring:
  config:
    on-profile: ci,test
  datasource:
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME:org.h2.Driver}
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:bank}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        format_sql: true
  sql:
    init:
      mode: embedded

logging.level.org.springframework:
  orm:
    jpa: INFO
    jpa.JpaTransactionManager: DEBUG
  transaction: INFO
  transaction.interceptor: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY:5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA}
    expiration-ms: ${SECURITY_JWT_EXPIRATION_MS:3600000}

encryptor:
  aes:
    iv-length: ${ENCRYPTOR_AES_IV_LENGTH:12}
    tag-length: ${ENCRYPTOR_AES_TAG_LENGTH:16}
    passphrase: ${ENCRYPTOR_AES_PASSPHRASE:testPassphrase123!}
